global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'etcd'
    static_configs:
      - targets: ['etcd:2379']
      - targets: ['etcd:2381']
    metrics_path: '/metrics'
    scheme: 'http'
